// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module eucHW_eucHW_Pipeline_VITIS_LOOP_34_24 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_array_31_6_reload,
        out_array_30_6_reload,
        out_array_29_6_reload,
        out_array_28_6_reload,
        out_array_27_6_reload,
        out_array_26_6_reload,
        out_array_25_6_reload,
        out_array_24_6_reload,
        out_array_23_6_reload,
        out_array_22_6_reload,
        out_array_21_6_reload,
        out_array_20_6_reload,
        out_array_19_6_reload,
        out_array_18_6_reload,
        out_array_17_6_reload,
        out_array_16_6_reload,
        out_array_15_6_reload,
        out_array_14_6_reload,
        out_array_13_6_reload,
        out_array_12_6_reload,
        out_array_11_6_reload,
        out_array_10_6_reload,
        out_array_9_6_reload,
        out_array_8_6_reload,
        out_array_7_6_reload,
        out_array_6_6_reload,
        out_array_5_6_reload,
        out_array_4_6_reload,
        out_array_3_6_reload,
        out_array_2_6_reload,
        out_array_1_6_reload,
        out_array_0_6_reload,
        out_array_62_6_reload,
        out_array_61_6_reload,
        out_array_60_6_reload,
        out_array_59_6_reload,
        out_array_58_6_reload,
        out_array_57_6_reload,
        out_array_56_6_reload,
        out_array_55_6_reload,
        out_array_54_6_reload,
        out_array_53_6_reload,
        out_array_52_6_reload,
        out_array_51_6_reload,
        out_array_50_6_reload,
        out_array_49_6_reload,
        out_array_48_6_reload,
        out_array_47_6_reload,
        out_array_46_6_reload,
        out_array_45_6_reload,
        out_array_44_6_reload,
        out_array_43_6_reload,
        out_array_42_6_reload,
        out_array_41_6_reload,
        out_array_40_6_reload,
        out_array_39_6_reload,
        out_array_38_6_reload,
        out_array_37_6_reload,
        out_array_36_6_reload,
        out_array_35_6_reload,
        out_array_34_6_reload,
        out_array_33_6_reload,
        out_array_32_6_reload,
        out_array_63_6_reload,
        out_array_31_8_out,
        out_array_31_8_out_ap_vld,
        out_array_30_8_out,
        out_array_30_8_out_ap_vld,
        out_array_29_8_out,
        out_array_29_8_out_ap_vld,
        out_array_28_8_out,
        out_array_28_8_out_ap_vld,
        out_array_27_8_out,
        out_array_27_8_out_ap_vld,
        out_array_26_8_out,
        out_array_26_8_out_ap_vld,
        out_array_25_8_out,
        out_array_25_8_out_ap_vld,
        out_array_24_8_out,
        out_array_24_8_out_ap_vld,
        out_array_23_8_out,
        out_array_23_8_out_ap_vld,
        out_array_22_8_out,
        out_array_22_8_out_ap_vld,
        out_array_21_8_out,
        out_array_21_8_out_ap_vld,
        out_array_20_8_out,
        out_array_20_8_out_ap_vld,
        out_array_19_8_out,
        out_array_19_8_out_ap_vld,
        out_array_18_8_out,
        out_array_18_8_out_ap_vld,
        out_array_17_8_out,
        out_array_17_8_out_ap_vld,
        out_array_16_8_out,
        out_array_16_8_out_ap_vld,
        out_array_15_8_out,
        out_array_15_8_out_ap_vld,
        out_array_14_8_out,
        out_array_14_8_out_ap_vld,
        out_array_13_8_out,
        out_array_13_8_out_ap_vld,
        out_array_12_8_out,
        out_array_12_8_out_ap_vld,
        out_array_11_8_out,
        out_array_11_8_out_ap_vld,
        out_array_10_8_out,
        out_array_10_8_out_ap_vld,
        out_array_9_8_out,
        out_array_9_8_out_ap_vld,
        out_array_8_8_out,
        out_array_8_8_out_ap_vld,
        out_array_7_8_out,
        out_array_7_8_out_ap_vld,
        out_array_6_8_out,
        out_array_6_8_out_ap_vld,
        out_array_5_8_out,
        out_array_5_8_out_ap_vld,
        out_array_4_8_out,
        out_array_4_8_out_ap_vld,
        out_array_3_8_out,
        out_array_3_8_out_ap_vld,
        out_array_2_8_out,
        out_array_2_8_out_ap_vld,
        out_array_1_8_out,
        out_array_1_8_out_ap_vld,
        out_array_0_8_out,
        out_array_0_8_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] out_array_31_6_reload;
input  [31:0] out_array_30_6_reload;
input  [31:0] out_array_29_6_reload;
input  [31:0] out_array_28_6_reload;
input  [31:0] out_array_27_6_reload;
input  [31:0] out_array_26_6_reload;
input  [31:0] out_array_25_6_reload;
input  [31:0] out_array_24_6_reload;
input  [31:0] out_array_23_6_reload;
input  [31:0] out_array_22_6_reload;
input  [31:0] out_array_21_6_reload;
input  [31:0] out_array_20_6_reload;
input  [31:0] out_array_19_6_reload;
input  [31:0] out_array_18_6_reload;
input  [31:0] out_array_17_6_reload;
input  [31:0] out_array_16_6_reload;
input  [31:0] out_array_15_6_reload;
input  [31:0] out_array_14_6_reload;
input  [31:0] out_array_13_6_reload;
input  [31:0] out_array_12_6_reload;
input  [31:0] out_array_11_6_reload;
input  [31:0] out_array_10_6_reload;
input  [31:0] out_array_9_6_reload;
input  [31:0] out_array_8_6_reload;
input  [31:0] out_array_7_6_reload;
input  [31:0] out_array_6_6_reload;
input  [31:0] out_array_5_6_reload;
input  [31:0] out_array_4_6_reload;
input  [31:0] out_array_3_6_reload;
input  [31:0] out_array_2_6_reload;
input  [31:0] out_array_1_6_reload;
input  [31:0] out_array_0_6_reload;
input  [31:0] out_array_62_6_reload;
input  [31:0] out_array_61_6_reload;
input  [31:0] out_array_60_6_reload;
input  [31:0] out_array_59_6_reload;
input  [31:0] out_array_58_6_reload;
input  [31:0] out_array_57_6_reload;
input  [31:0] out_array_56_6_reload;
input  [31:0] out_array_55_6_reload;
input  [31:0] out_array_54_6_reload;
input  [31:0] out_array_53_6_reload;
input  [31:0] out_array_52_6_reload;
input  [31:0] out_array_51_6_reload;
input  [31:0] out_array_50_6_reload;
input  [31:0] out_array_49_6_reload;
input  [31:0] out_array_48_6_reload;
input  [31:0] out_array_47_6_reload;
input  [31:0] out_array_46_6_reload;
input  [31:0] out_array_45_6_reload;
input  [31:0] out_array_44_6_reload;
input  [31:0] out_array_43_6_reload;
input  [31:0] out_array_42_6_reload;
input  [31:0] out_array_41_6_reload;
input  [31:0] out_array_40_6_reload;
input  [31:0] out_array_39_6_reload;
input  [31:0] out_array_38_6_reload;
input  [31:0] out_array_37_6_reload;
input  [31:0] out_array_36_6_reload;
input  [31:0] out_array_35_6_reload;
input  [31:0] out_array_34_6_reload;
input  [31:0] out_array_33_6_reload;
input  [31:0] out_array_32_6_reload;
input  [31:0] out_array_63_6_reload;
output  [31:0] out_array_31_8_out;
output   out_array_31_8_out_ap_vld;
output  [31:0] out_array_30_8_out;
output   out_array_30_8_out_ap_vld;
output  [31:0] out_array_29_8_out;
output   out_array_29_8_out_ap_vld;
output  [31:0] out_array_28_8_out;
output   out_array_28_8_out_ap_vld;
output  [31:0] out_array_27_8_out;
output   out_array_27_8_out_ap_vld;
output  [31:0] out_array_26_8_out;
output   out_array_26_8_out_ap_vld;
output  [31:0] out_array_25_8_out;
output   out_array_25_8_out_ap_vld;
output  [31:0] out_array_24_8_out;
output   out_array_24_8_out_ap_vld;
output  [31:0] out_array_23_8_out;
output   out_array_23_8_out_ap_vld;
output  [31:0] out_array_22_8_out;
output   out_array_22_8_out_ap_vld;
output  [31:0] out_array_21_8_out;
output   out_array_21_8_out_ap_vld;
output  [31:0] out_array_20_8_out;
output   out_array_20_8_out_ap_vld;
output  [31:0] out_array_19_8_out;
output   out_array_19_8_out_ap_vld;
output  [31:0] out_array_18_8_out;
output   out_array_18_8_out_ap_vld;
output  [31:0] out_array_17_8_out;
output   out_array_17_8_out_ap_vld;
output  [31:0] out_array_16_8_out;
output   out_array_16_8_out_ap_vld;
output  [31:0] out_array_15_8_out;
output   out_array_15_8_out_ap_vld;
output  [31:0] out_array_14_8_out;
output   out_array_14_8_out_ap_vld;
output  [31:0] out_array_13_8_out;
output   out_array_13_8_out_ap_vld;
output  [31:0] out_array_12_8_out;
output   out_array_12_8_out_ap_vld;
output  [31:0] out_array_11_8_out;
output   out_array_11_8_out_ap_vld;
output  [31:0] out_array_10_8_out;
output   out_array_10_8_out_ap_vld;
output  [31:0] out_array_9_8_out;
output   out_array_9_8_out_ap_vld;
output  [31:0] out_array_8_8_out;
output   out_array_8_8_out_ap_vld;
output  [31:0] out_array_7_8_out;
output   out_array_7_8_out_ap_vld;
output  [31:0] out_array_6_8_out;
output   out_array_6_8_out_ap_vld;
output  [31:0] out_array_5_8_out;
output   out_array_5_8_out_ap_vld;
output  [31:0] out_array_4_8_out;
output   out_array_4_8_out_ap_vld;
output  [31:0] out_array_3_8_out;
output   out_array_3_8_out_ap_vld;
output  [31:0] out_array_2_8_out;
output   out_array_2_8_out_ap_vld;
output  [31:0] out_array_1_8_out;
output   out_array_1_8_out_ap_vld;
output  [31:0] out_array_0_8_out;
output   out_array_0_8_out_ap_vld;

reg ap_idle;
reg out_array_31_8_out_ap_vld;
reg out_array_30_8_out_ap_vld;
reg out_array_29_8_out_ap_vld;
reg out_array_28_8_out_ap_vld;
reg out_array_27_8_out_ap_vld;
reg out_array_26_8_out_ap_vld;
reg out_array_25_8_out_ap_vld;
reg out_array_24_8_out_ap_vld;
reg out_array_23_8_out_ap_vld;
reg out_array_22_8_out_ap_vld;
reg out_array_21_8_out_ap_vld;
reg out_array_20_8_out_ap_vld;
reg out_array_19_8_out_ap_vld;
reg out_array_18_8_out_ap_vld;
reg out_array_17_8_out_ap_vld;
reg out_array_16_8_out_ap_vld;
reg out_array_15_8_out_ap_vld;
reg out_array_14_8_out_ap_vld;
reg out_array_13_8_out_ap_vld;
reg out_array_12_8_out_ap_vld;
reg out_array_11_8_out_ap_vld;
reg out_array_10_8_out_ap_vld;
reg out_array_9_8_out_ap_vld;
reg out_array_8_8_out_ap_vld;
reg out_array_7_8_out_ap_vld;
reg out_array_6_8_out_ap_vld;
reg out_array_5_8_out_ap_vld;
reg out_array_4_8_out_ap_vld;
reg out_array_3_8_out_ap_vld;
reg out_array_2_8_out_ap_vld;
reg out_array_1_8_out_ap_vld;
reg out_array_0_8_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln34_fu_1192_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] trunc_ln38_fu_1300_p1;
reg   [4:0] trunc_ln38_reg_2653;
wire   [31:0] tem1_fu_1304_p34;
reg   [31:0] tem1_reg_2657;
wire   [31:0] select_ln39_50_fu_1902_p3;
reg   [31:0] select_ln39_50_reg_2662;
wire   [0:0] or_ln39_38_fu_1910_p2;
reg   [0:0] or_ln39_38_reg_2667;
wire   [31:0] select_ln39_51_fu_1916_p3;
reg   [31:0] select_ln39_51_reg_2672;
reg   [5:0] i_4_fu_284;
wire   [5:0] add_ln34_fu_1198_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [31:0] out_array_1_fu_288;
wire   [31:0] out_array_1_68_fu_1934_p2;
reg   [31:0] ap_sig_allocacmp_out_array_1_load_5;
reg   [31:0] out_array_1_36_fu_292;
reg   [31:0] ap_sig_allocacmp_out_array_1_36_load_1;
reg   [31:0] out_array_1_37_fu_296;
reg   [31:0] ap_sig_allocacmp_out_array_1_37_load_1;
reg   [31:0] out_array_1_38_fu_300;
reg   [31:0] ap_sig_allocacmp_out_array_1_38_load_1;
reg   [31:0] out_array_1_39_fu_304;
reg   [31:0] ap_sig_allocacmp_out_array_1_39_load_1;
reg   [31:0] out_array_1_40_fu_308;
reg   [31:0] ap_sig_allocacmp_out_array_1_40_load_1;
reg   [31:0] out_array_1_41_fu_312;
reg   [31:0] ap_sig_allocacmp_out_array_1_41_load_1;
reg   [31:0] out_array_1_42_fu_316;
reg   [31:0] ap_sig_allocacmp_out_array_1_42_load_1;
reg   [31:0] out_array_1_43_fu_320;
reg   [31:0] ap_sig_allocacmp_out_array_1_43_load_1;
reg   [31:0] out_array_1_44_fu_324;
reg   [31:0] ap_sig_allocacmp_out_array_1_44_load_1;
reg   [31:0] out_array_1_45_fu_328;
reg   [31:0] ap_sig_allocacmp_out_array_1_45_load_1;
reg   [31:0] out_array_1_46_fu_332;
reg   [31:0] ap_sig_allocacmp_out_array_1_46_load_1;
reg   [31:0] out_array_1_47_fu_336;
reg   [31:0] ap_sig_allocacmp_out_array_1_47_load_1;
reg   [31:0] out_array_1_48_fu_340;
reg   [31:0] ap_sig_allocacmp_out_array_1_48_load_1;
reg   [31:0] out_array_1_49_fu_344;
reg   [31:0] ap_sig_allocacmp_out_array_1_49_load_1;
reg   [31:0] out_array_1_50_fu_348;
reg   [31:0] ap_sig_allocacmp_out_array_1_50_load_1;
reg   [31:0] out_array_1_51_fu_352;
reg   [31:0] ap_sig_allocacmp_out_array_1_51_load_1;
reg   [31:0] out_array_1_52_fu_356;
reg   [31:0] ap_sig_allocacmp_out_array_1_52_load_1;
reg   [31:0] out_array_1_53_fu_360;
reg   [31:0] ap_sig_allocacmp_out_array_1_53_load_1;
reg   [31:0] out_array_1_54_fu_364;
reg   [31:0] ap_sig_allocacmp_out_array_1_54_load_1;
reg   [31:0] out_array_1_55_fu_368;
reg   [31:0] ap_sig_allocacmp_out_array_1_55_load_1;
reg   [31:0] out_array_1_56_fu_372;
reg   [31:0] ap_sig_allocacmp_out_array_1_56_load_1;
reg   [31:0] out_array_1_57_fu_376;
reg   [31:0] ap_sig_allocacmp_out_array_1_57_load_1;
reg   [31:0] out_array_1_58_fu_380;
reg   [31:0] ap_sig_allocacmp_out_array_1_58_load_1;
reg   [31:0] out_array_1_59_fu_384;
reg   [31:0] ap_sig_allocacmp_out_array_1_59_load_1;
reg   [31:0] out_array_1_60_fu_388;
reg   [31:0] ap_sig_allocacmp_out_array_1_60_load_1;
reg   [31:0] out_array_1_61_fu_392;
reg   [31:0] ap_sig_allocacmp_out_array_1_61_load_1;
reg   [31:0] out_array_1_62_fu_396;
reg   [31:0] ap_sig_allocacmp_out_array_1_62_load_1;
reg   [31:0] out_array_1_63_fu_400;
reg   [31:0] ap_sig_allocacmp_out_array_1_63_load_1;
reg   [31:0] out_array_1_64_fu_404;
reg   [31:0] ap_sig_allocacmp_out_array_1_64_load_1;
reg   [31:0] out_array_1_65_fu_408;
reg   [31:0] ap_sig_allocacmp_out_array_1_65_load_1;
reg   [31:0] out_array_1_66_fu_412;
reg   [31:0] ap_sig_allocacmp_out_array_1_66_load_1;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln39_52_fu_1554_p2;
wire   [0:0] icmp_ln39_51_fu_1548_p2;
wire   [0:0] icmp_ln39_50_fu_1542_p2;
wire   [0:0] icmp_ln39_49_fu_1536_p2;
wire   [0:0] icmp_ln39_48_fu_1530_p2;
wire   [0:0] icmp_ln39_47_fu_1524_p2;
wire   [0:0] icmp_ln39_46_fu_1518_p2;
wire   [0:0] icmp_ln39_45_fu_1512_p2;
wire   [0:0] icmp_ln39_44_fu_1506_p2;
wire   [0:0] icmp_ln39_43_fu_1500_p2;
wire   [0:0] icmp_ln39_42_fu_1494_p2;
wire   [0:0] icmp_ln39_41_fu_1488_p2;
wire   [0:0] icmp_ln39_40_fu_1482_p2;
wire   [0:0] icmp_ln39_39_fu_1476_p2;
wire   [0:0] icmp_ln39_38_fu_1470_p2;
wire   [0:0] icmp_ln39_37_fu_1464_p2;
wire   [0:0] icmp_ln39_36_fu_1458_p2;
wire   [0:0] icmp_ln39_35_fu_1452_p2;
wire   [0:0] icmp_ln39_34_fu_1446_p2;
wire   [0:0] icmp_ln39_33_fu_1440_p2;
wire   [0:0] icmp_ln39_32_fu_1434_p2;
wire   [0:0] icmp_ln39_31_fu_1428_p2;
wire   [0:0] icmp_ln39_30_fu_1422_p2;
wire   [0:0] icmp_ln39_29_fu_1416_p2;
wire   [0:0] icmp_ln39_28_fu_1410_p2;
wire   [0:0] icmp_ln39_27_fu_1404_p2;
wire   [0:0] icmp_ln39_26_fu_1398_p2;
wire   [0:0] icmp_ln39_25_fu_1392_p2;
wire   [0:0] icmp_ln39_24_fu_1386_p2;
wire   [0:0] icmp_ln39_23_fu_1380_p2;
wire   [0:0] icmp_ln39_fu_1374_p2;
wire   [0:0] or_ln39_fu_1566_p2;
wire   [31:0] select_ln39_fu_1560_p3;
wire   [31:0] select_ln39_23_fu_1572_p3;
wire   [0:0] or_ln39_14_fu_1578_p2;
wire   [0:0] or_ln39_15_fu_1590_p2;
wire   [31:0] select_ln39_24_fu_1584_p3;
wire   [31:0] select_ln39_25_fu_1596_p3;
wire   [0:0] or_ln39_16_fu_1602_p2;
wire   [0:0] or_ln39_17_fu_1614_p2;
wire   [31:0] select_ln39_26_fu_1608_p3;
wire   [31:0] select_ln39_27_fu_1620_p3;
wire   [0:0] or_ln39_18_fu_1626_p2;
wire   [0:0] or_ln39_19_fu_1638_p2;
wire   [31:0] select_ln39_28_fu_1632_p3;
wire   [31:0] select_ln39_29_fu_1644_p3;
wire   [0:0] or_ln39_20_fu_1650_p2;
wire   [0:0] or_ln39_21_fu_1662_p2;
wire   [31:0] select_ln39_30_fu_1656_p3;
wire   [31:0] select_ln39_31_fu_1668_p3;
wire   [0:0] or_ln39_22_fu_1674_p2;
wire   [0:0] or_ln39_23_fu_1686_p2;
wire   [31:0] select_ln39_32_fu_1680_p3;
wire   [31:0] select_ln39_33_fu_1692_p3;
wire   [0:0] or_ln39_24_fu_1698_p2;
wire   [0:0] or_ln39_25_fu_1710_p2;
wire   [31:0] select_ln39_34_fu_1704_p3;
wire   [31:0] select_ln39_35_fu_1716_p3;
wire   [0:0] or_ln39_26_fu_1722_p2;
wire   [0:0] or_ln39_27_fu_1734_p2;
wire   [31:0] select_ln39_36_fu_1728_p3;
wire   [31:0] select_ln39_37_fu_1740_p3;
wire   [0:0] or_ln39_28_fu_1754_p2;
wire   [31:0] select_ln39_38_fu_1746_p3;
wire   [31:0] select_ln39_39_fu_1760_p3;
wire   [0:0] or_ln39_29_fu_1768_p2;
wire   [0:0] or_ln39_30_fu_1782_p2;
wire   [31:0] select_ln39_40_fu_1774_p3;
wire   [31:0] select_ln39_41_fu_1788_p3;
wire   [0:0] or_ln39_31_fu_1796_p2;
wire   [0:0] or_ln39_32_fu_1810_p2;
wire   [31:0] select_ln39_42_fu_1802_p3;
wire   [31:0] select_ln39_43_fu_1816_p3;
wire   [0:0] or_ln39_33_fu_1824_p2;
wire   [0:0] or_ln39_34_fu_1838_p2;
wire   [31:0] select_ln39_44_fu_1830_p3;
wire   [31:0] select_ln39_45_fu_1844_p3;
wire   [0:0] or_ln39_35_fu_1860_p2;
wire   [31:0] select_ln39_46_fu_1852_p3;
wire   [31:0] select_ln39_47_fu_1866_p3;
wire   [0:0] or_ln39_36_fu_1874_p2;
wire   [0:0] or_ln39_37_fu_1888_p2;
wire   [31:0] select_ln39_48_fu_1880_p3;
wire   [31:0] select_ln39_49_fu_1894_p3;
wire   [31:0] tem2_fu_1929_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

eucHW_mux_325_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_325_32_1_1_U2887(
    .din0(ap_sig_allocacmp_out_array_1_load_5),
    .din1(ap_sig_allocacmp_out_array_1_36_load_1),
    .din2(ap_sig_allocacmp_out_array_1_37_load_1),
    .din3(ap_sig_allocacmp_out_array_1_38_load_1),
    .din4(ap_sig_allocacmp_out_array_1_39_load_1),
    .din5(ap_sig_allocacmp_out_array_1_40_load_1),
    .din6(ap_sig_allocacmp_out_array_1_41_load_1),
    .din7(ap_sig_allocacmp_out_array_1_42_load_1),
    .din8(ap_sig_allocacmp_out_array_1_43_load_1),
    .din9(ap_sig_allocacmp_out_array_1_44_load_1),
    .din10(ap_sig_allocacmp_out_array_1_45_load_1),
    .din11(ap_sig_allocacmp_out_array_1_46_load_1),
    .din12(ap_sig_allocacmp_out_array_1_47_load_1),
    .din13(ap_sig_allocacmp_out_array_1_48_load_1),
    .din14(ap_sig_allocacmp_out_array_1_49_load_1),
    .din15(ap_sig_allocacmp_out_array_1_50_load_1),
    .din16(ap_sig_allocacmp_out_array_1_51_load_1),
    .din17(ap_sig_allocacmp_out_array_1_52_load_1),
    .din18(ap_sig_allocacmp_out_array_1_53_load_1),
    .din19(ap_sig_allocacmp_out_array_1_54_load_1),
    .din20(ap_sig_allocacmp_out_array_1_55_load_1),
    .din21(ap_sig_allocacmp_out_array_1_56_load_1),
    .din22(ap_sig_allocacmp_out_array_1_57_load_1),
    .din23(ap_sig_allocacmp_out_array_1_58_load_1),
    .din24(ap_sig_allocacmp_out_array_1_59_load_1),
    .din25(ap_sig_allocacmp_out_array_1_60_load_1),
    .din26(ap_sig_allocacmp_out_array_1_61_load_1),
    .din27(ap_sig_allocacmp_out_array_1_62_load_1),
    .din28(ap_sig_allocacmp_out_array_1_63_load_1),
    .din29(ap_sig_allocacmp_out_array_1_64_load_1),
    .din30(ap_sig_allocacmp_out_array_1_65_load_1),
    .din31(ap_sig_allocacmp_out_array_1_66_load_1),
    .din32(trunc_ln38_fu_1300_p1),
    .dout(tem1_fu_1304_p34)
);

eucHW_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_4_fu_284 <= 6'd0;
        end else if (((icmp_ln34_fu_1192_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_4_fu_284 <= add_ln34_fu_1198_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_36_fu_292 <= out_array_1_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_36_fu_292 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_37_fu_296 <= out_array_2_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_37_fu_296 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_38_fu_300 <= out_array_3_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_38_fu_300 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_39_fu_304 <= out_array_4_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd4) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_39_fu_304 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_40_fu_308 <= out_array_5_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd5) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_40_fu_308 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_41_fu_312 <= out_array_6_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd6) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_41_fu_312 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_42_fu_316 <= out_array_7_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd7) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_42_fu_316 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_43_fu_320 <= out_array_8_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd8) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_43_fu_320 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_44_fu_324 <= out_array_9_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd9) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_44_fu_324 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_45_fu_328 <= out_array_10_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd10) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_45_fu_328 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_46_fu_332 <= out_array_11_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd11) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_46_fu_332 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_47_fu_336 <= out_array_12_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd12) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_47_fu_336 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_48_fu_340 <= out_array_13_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd13) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_48_fu_340 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_49_fu_344 <= out_array_14_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd14) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_49_fu_344 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_50_fu_348 <= out_array_15_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd15) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_50_fu_348 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_51_fu_352 <= out_array_16_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd16) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_51_fu_352 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_52_fu_356 <= out_array_17_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd17) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_52_fu_356 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_53_fu_360 <= out_array_18_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd18) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_53_fu_360 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_54_fu_364 <= out_array_19_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd19) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_54_fu_364 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_55_fu_368 <= out_array_20_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd20) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_55_fu_368 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_56_fu_372 <= out_array_21_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd21) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_56_fu_372 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_57_fu_376 <= out_array_22_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd22) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_57_fu_376 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_58_fu_380 <= out_array_23_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd23) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_58_fu_380 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_59_fu_384 <= out_array_24_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd24) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_59_fu_384 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_60_fu_388 <= out_array_25_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd25) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_60_fu_388 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_61_fu_392 <= out_array_26_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd26) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_61_fu_392 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_62_fu_396 <= out_array_27_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd27) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_62_fu_396 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_63_fu_400 <= out_array_28_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd28) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_63_fu_400 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_64_fu_404 <= out_array_29_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd29) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_64_fu_404 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_65_fu_408 <= out_array_30_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd30) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_65_fu_408 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_66_fu_412 <= out_array_31_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd31) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_66_fu_412 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_array_1_fu_288 <= out_array_0_6_reload;
        end else if (((trunc_ln38_reg_2653 == 5'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            out_array_1_fu_288 <= out_array_1_68_fu_1934_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln39_38_reg_2667 <= or_ln39_38_fu_1910_p2;
        select_ln39_50_reg_2662 <= select_ln39_50_fu_1902_p3;
        select_ln39_51_reg_2672 <= select_ln39_51_fu_1916_p3;
        tem1_reg_2657 <= tem1_fu_1304_p34;
        trunc_ln38_reg_2653 <= trunc_ln38_fu_1300_p1;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_36_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_36_load_1 = out_array_1_36_fu_292;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_37_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_37_load_1 = out_array_1_37_fu_296;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_38_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_38_load_1 = out_array_1_38_fu_300;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd4) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_39_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_39_load_1 = out_array_1_39_fu_304;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd5) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_40_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_40_load_1 = out_array_1_40_fu_308;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd6) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_41_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_41_load_1 = out_array_1_41_fu_312;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd7) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_42_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_42_load_1 = out_array_1_42_fu_316;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd8) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_43_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_43_load_1 = out_array_1_43_fu_320;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd9) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_44_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_44_load_1 = out_array_1_44_fu_324;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd10) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_45_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_45_load_1 = out_array_1_45_fu_328;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd11) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_46_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_46_load_1 = out_array_1_46_fu_332;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd12) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_47_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_47_load_1 = out_array_1_47_fu_336;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd13) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_48_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_48_load_1 = out_array_1_48_fu_340;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd14) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_49_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_49_load_1 = out_array_1_49_fu_344;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd15) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_50_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_50_load_1 = out_array_1_50_fu_348;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd16) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_51_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_51_load_1 = out_array_1_51_fu_352;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd17) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_52_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_52_load_1 = out_array_1_52_fu_356;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd18) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_53_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_53_load_1 = out_array_1_53_fu_360;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd19) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_54_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_54_load_1 = out_array_1_54_fu_364;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd20) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_55_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_55_load_1 = out_array_1_55_fu_368;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd21) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_56_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_56_load_1 = out_array_1_56_fu_372;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd22) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_57_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_57_load_1 = out_array_1_57_fu_376;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd23) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_58_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_58_load_1 = out_array_1_58_fu_380;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd24) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_59_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_59_load_1 = out_array_1_59_fu_384;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd25) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_60_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_60_load_1 = out_array_1_60_fu_388;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd26) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_61_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_61_load_1 = out_array_1_61_fu_392;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd27) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_62_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_62_load_1 = out_array_1_62_fu_396;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd28) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_63_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_63_load_1 = out_array_1_63_fu_400;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd29) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_64_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_64_load_1 = out_array_1_64_fu_404;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd30) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_65_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_65_load_1 = out_array_1_65_fu_408;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd31) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_66_load_1 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_66_load_1 = out_array_1_66_fu_412;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (trunc_ln38_reg_2653 == 5'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_out_array_1_load_5 = out_array_1_68_fu_1934_p2;
    end else begin
        ap_sig_allocacmp_out_array_1_load_5 = out_array_1_fu_288;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_0_8_out_ap_vld = 1'b1;
    end else begin
        out_array_0_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_10_8_out_ap_vld = 1'b1;
    end else begin
        out_array_10_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_11_8_out_ap_vld = 1'b1;
    end else begin
        out_array_11_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_12_8_out_ap_vld = 1'b1;
    end else begin
        out_array_12_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_13_8_out_ap_vld = 1'b1;
    end else begin
        out_array_13_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_14_8_out_ap_vld = 1'b1;
    end else begin
        out_array_14_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_15_8_out_ap_vld = 1'b1;
    end else begin
        out_array_15_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_16_8_out_ap_vld = 1'b1;
    end else begin
        out_array_16_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_17_8_out_ap_vld = 1'b1;
    end else begin
        out_array_17_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_18_8_out_ap_vld = 1'b1;
    end else begin
        out_array_18_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_19_8_out_ap_vld = 1'b1;
    end else begin
        out_array_19_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_1_8_out_ap_vld = 1'b1;
    end else begin
        out_array_1_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_20_8_out_ap_vld = 1'b1;
    end else begin
        out_array_20_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_21_8_out_ap_vld = 1'b1;
    end else begin
        out_array_21_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_22_8_out_ap_vld = 1'b1;
    end else begin
        out_array_22_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_23_8_out_ap_vld = 1'b1;
    end else begin
        out_array_23_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_24_8_out_ap_vld = 1'b1;
    end else begin
        out_array_24_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_25_8_out_ap_vld = 1'b1;
    end else begin
        out_array_25_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_26_8_out_ap_vld = 1'b1;
    end else begin
        out_array_26_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_27_8_out_ap_vld = 1'b1;
    end else begin
        out_array_27_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_28_8_out_ap_vld = 1'b1;
    end else begin
        out_array_28_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_29_8_out_ap_vld = 1'b1;
    end else begin
        out_array_29_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_2_8_out_ap_vld = 1'b1;
    end else begin
        out_array_2_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_30_8_out_ap_vld = 1'b1;
    end else begin
        out_array_30_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_31_8_out_ap_vld = 1'b1;
    end else begin
        out_array_31_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_3_8_out_ap_vld = 1'b1;
    end else begin
        out_array_3_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_4_8_out_ap_vld = 1'b1;
    end else begin
        out_array_4_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_5_8_out_ap_vld = 1'b1;
    end else begin
        out_array_5_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_6_8_out_ap_vld = 1'b1;
    end else begin
        out_array_6_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_7_8_out_ap_vld = 1'b1;
    end else begin
        out_array_7_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_8_8_out_ap_vld = 1'b1;
    end else begin
        out_array_8_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_1192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_array_9_8_out_ap_vld = 1'b1;
    end else begin
        out_array_9_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln34_fu_1198_p2 = (i_4_fu_284 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln34_fu_1192_p2 = ((i_4_fu_284 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln39_23_fu_1380_p2 = ((trunc_ln38_fu_1300_p1 == 5'd1) ? 1'b1 : 1'b0);

assign icmp_ln39_24_fu_1386_p2 = ((trunc_ln38_fu_1300_p1 == 5'd2) ? 1'b1 : 1'b0);

assign icmp_ln39_25_fu_1392_p2 = ((trunc_ln38_fu_1300_p1 == 5'd3) ? 1'b1 : 1'b0);

assign icmp_ln39_26_fu_1398_p2 = ((trunc_ln38_fu_1300_p1 == 5'd4) ? 1'b1 : 1'b0);

assign icmp_ln39_27_fu_1404_p2 = ((trunc_ln38_fu_1300_p1 == 5'd5) ? 1'b1 : 1'b0);

assign icmp_ln39_28_fu_1410_p2 = ((trunc_ln38_fu_1300_p1 == 5'd6) ? 1'b1 : 1'b0);

assign icmp_ln39_29_fu_1416_p2 = ((trunc_ln38_fu_1300_p1 == 5'd7) ? 1'b1 : 1'b0);

assign icmp_ln39_30_fu_1422_p2 = ((trunc_ln38_fu_1300_p1 == 5'd8) ? 1'b1 : 1'b0);

assign icmp_ln39_31_fu_1428_p2 = ((trunc_ln38_fu_1300_p1 == 5'd9) ? 1'b1 : 1'b0);

assign icmp_ln39_32_fu_1434_p2 = ((trunc_ln38_fu_1300_p1 == 5'd10) ? 1'b1 : 1'b0);

assign icmp_ln39_33_fu_1440_p2 = ((trunc_ln38_fu_1300_p1 == 5'd11) ? 1'b1 : 1'b0);

assign icmp_ln39_34_fu_1446_p2 = ((trunc_ln38_fu_1300_p1 == 5'd12) ? 1'b1 : 1'b0);

assign icmp_ln39_35_fu_1452_p2 = ((trunc_ln38_fu_1300_p1 == 5'd13) ? 1'b1 : 1'b0);

assign icmp_ln39_36_fu_1458_p2 = ((trunc_ln38_fu_1300_p1 == 5'd14) ? 1'b1 : 1'b0);

assign icmp_ln39_37_fu_1464_p2 = ((trunc_ln38_fu_1300_p1 == 5'd15) ? 1'b1 : 1'b0);

assign icmp_ln39_38_fu_1470_p2 = ((trunc_ln38_fu_1300_p1 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln39_39_fu_1476_p2 = ((trunc_ln38_fu_1300_p1 == 5'd17) ? 1'b1 : 1'b0);

assign icmp_ln39_40_fu_1482_p2 = ((trunc_ln38_fu_1300_p1 == 5'd18) ? 1'b1 : 1'b0);

assign icmp_ln39_41_fu_1488_p2 = ((trunc_ln38_fu_1300_p1 == 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln39_42_fu_1494_p2 = ((trunc_ln38_fu_1300_p1 == 5'd20) ? 1'b1 : 1'b0);

assign icmp_ln39_43_fu_1500_p2 = ((trunc_ln38_fu_1300_p1 == 5'd21) ? 1'b1 : 1'b0);

assign icmp_ln39_44_fu_1506_p2 = ((trunc_ln38_fu_1300_p1 == 5'd22) ? 1'b1 : 1'b0);

assign icmp_ln39_45_fu_1512_p2 = ((trunc_ln38_fu_1300_p1 == 5'd23) ? 1'b1 : 1'b0);

assign icmp_ln39_46_fu_1518_p2 = ((trunc_ln38_fu_1300_p1 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln39_47_fu_1524_p2 = ((trunc_ln38_fu_1300_p1 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln39_48_fu_1530_p2 = ((trunc_ln38_fu_1300_p1 == 5'd26) ? 1'b1 : 1'b0);

assign icmp_ln39_49_fu_1536_p2 = ((trunc_ln38_fu_1300_p1 == 5'd27) ? 1'b1 : 1'b0);

assign icmp_ln39_50_fu_1542_p2 = ((trunc_ln38_fu_1300_p1 == 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln39_51_fu_1548_p2 = ((trunc_ln38_fu_1300_p1 == 5'd29) ? 1'b1 : 1'b0);

assign icmp_ln39_52_fu_1554_p2 = ((trunc_ln38_fu_1300_p1 == 5'd30) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_1374_p2 = ((trunc_ln38_fu_1300_p1 == 5'd0) ? 1'b1 : 1'b0);

assign or_ln39_14_fu_1578_p2 = (icmp_ln39_50_fu_1542_p2 | icmp_ln39_49_fu_1536_p2);

assign or_ln39_15_fu_1590_p2 = (icmp_ln39_48_fu_1530_p2 | icmp_ln39_47_fu_1524_p2);

assign or_ln39_16_fu_1602_p2 = (icmp_ln39_46_fu_1518_p2 | icmp_ln39_45_fu_1512_p2);

assign or_ln39_17_fu_1614_p2 = (icmp_ln39_44_fu_1506_p2 | icmp_ln39_43_fu_1500_p2);

assign or_ln39_18_fu_1626_p2 = (icmp_ln39_42_fu_1494_p2 | icmp_ln39_41_fu_1488_p2);

assign or_ln39_19_fu_1638_p2 = (icmp_ln39_40_fu_1482_p2 | icmp_ln39_39_fu_1476_p2);

assign or_ln39_20_fu_1650_p2 = (icmp_ln39_38_fu_1470_p2 | icmp_ln39_37_fu_1464_p2);

assign or_ln39_21_fu_1662_p2 = (icmp_ln39_36_fu_1458_p2 | icmp_ln39_35_fu_1452_p2);

assign or_ln39_22_fu_1674_p2 = (icmp_ln39_34_fu_1446_p2 | icmp_ln39_33_fu_1440_p2);

assign or_ln39_23_fu_1686_p2 = (icmp_ln39_32_fu_1434_p2 | icmp_ln39_31_fu_1428_p2);

assign or_ln39_24_fu_1698_p2 = (icmp_ln39_30_fu_1422_p2 | icmp_ln39_29_fu_1416_p2);

assign or_ln39_25_fu_1710_p2 = (icmp_ln39_28_fu_1410_p2 | icmp_ln39_27_fu_1404_p2);

assign or_ln39_26_fu_1722_p2 = (icmp_ln39_26_fu_1398_p2 | icmp_ln39_25_fu_1392_p2);

assign or_ln39_27_fu_1734_p2 = (icmp_ln39_24_fu_1386_p2 | icmp_ln39_23_fu_1380_p2);

assign or_ln39_28_fu_1754_p2 = (or_ln39_fu_1566_p2 | or_ln39_14_fu_1578_p2);

assign or_ln39_29_fu_1768_p2 = (or_ln39_16_fu_1602_p2 | or_ln39_15_fu_1590_p2);

assign or_ln39_30_fu_1782_p2 = (or_ln39_18_fu_1626_p2 | or_ln39_17_fu_1614_p2);

assign or_ln39_31_fu_1796_p2 = (or_ln39_20_fu_1650_p2 | or_ln39_19_fu_1638_p2);

assign or_ln39_32_fu_1810_p2 = (or_ln39_22_fu_1674_p2 | or_ln39_21_fu_1662_p2);

assign or_ln39_33_fu_1824_p2 = (or_ln39_24_fu_1698_p2 | or_ln39_23_fu_1686_p2);

assign or_ln39_34_fu_1838_p2 = (or_ln39_26_fu_1722_p2 | or_ln39_25_fu_1710_p2);

assign or_ln39_35_fu_1860_p2 = (or_ln39_29_fu_1768_p2 | or_ln39_28_fu_1754_p2);

assign or_ln39_36_fu_1874_p2 = (or_ln39_31_fu_1796_p2 | or_ln39_30_fu_1782_p2);

assign or_ln39_37_fu_1888_p2 = (or_ln39_33_fu_1824_p2 | or_ln39_32_fu_1810_p2);

assign or_ln39_38_fu_1910_p2 = (or_ln39_36_fu_1874_p2 | or_ln39_35_fu_1860_p2);

assign or_ln39_fu_1566_p2 = (icmp_ln39_52_fu_1554_p2 | icmp_ln39_51_fu_1548_p2);

assign out_array_0_8_out = out_array_1_fu_288;

assign out_array_10_8_out = out_array_1_45_fu_328;

assign out_array_11_8_out = out_array_1_46_fu_332;

assign out_array_12_8_out = out_array_1_47_fu_336;

assign out_array_13_8_out = out_array_1_48_fu_340;

assign out_array_14_8_out = out_array_1_49_fu_344;

assign out_array_15_8_out = out_array_1_50_fu_348;

assign out_array_16_8_out = out_array_1_51_fu_352;

assign out_array_17_8_out = out_array_1_52_fu_356;

assign out_array_18_8_out = out_array_1_53_fu_360;

assign out_array_19_8_out = out_array_1_54_fu_364;

assign out_array_1_68_fu_1934_p2 = (tem2_fu_1929_p3 + tem1_reg_2657);

assign out_array_1_8_out = out_array_1_36_fu_292;

assign out_array_20_8_out = out_array_1_55_fu_368;

assign out_array_21_8_out = out_array_1_56_fu_372;

assign out_array_22_8_out = out_array_1_57_fu_376;

assign out_array_23_8_out = out_array_1_58_fu_380;

assign out_array_24_8_out = out_array_1_59_fu_384;

assign out_array_25_8_out = out_array_1_60_fu_388;

assign out_array_26_8_out = out_array_1_61_fu_392;

assign out_array_27_8_out = out_array_1_62_fu_396;

assign out_array_28_8_out = out_array_1_63_fu_400;

assign out_array_29_8_out = out_array_1_64_fu_404;

assign out_array_2_8_out = out_array_1_37_fu_296;

assign out_array_30_8_out = out_array_1_65_fu_408;

assign out_array_31_8_out = out_array_1_66_fu_412;

assign out_array_3_8_out = out_array_1_38_fu_300;

assign out_array_4_8_out = out_array_1_39_fu_304;

assign out_array_5_8_out = out_array_1_40_fu_308;

assign out_array_6_8_out = out_array_1_41_fu_312;

assign out_array_7_8_out = out_array_1_42_fu_316;

assign out_array_8_8_out = out_array_1_43_fu_320;

assign out_array_9_8_out = out_array_1_44_fu_324;

assign select_ln39_23_fu_1572_p3 = ((icmp_ln39_50_fu_1542_p2[0:0] == 1'b1) ? out_array_60_6_reload : out_array_59_6_reload);

assign select_ln39_24_fu_1584_p3 = ((icmp_ln39_48_fu_1530_p2[0:0] == 1'b1) ? out_array_58_6_reload : out_array_57_6_reload);

assign select_ln39_25_fu_1596_p3 = ((icmp_ln39_46_fu_1518_p2[0:0] == 1'b1) ? out_array_56_6_reload : out_array_55_6_reload);

assign select_ln39_26_fu_1608_p3 = ((icmp_ln39_44_fu_1506_p2[0:0] == 1'b1) ? out_array_54_6_reload : out_array_53_6_reload);

assign select_ln39_27_fu_1620_p3 = ((icmp_ln39_42_fu_1494_p2[0:0] == 1'b1) ? out_array_52_6_reload : out_array_51_6_reload);

assign select_ln39_28_fu_1632_p3 = ((icmp_ln39_40_fu_1482_p2[0:0] == 1'b1) ? out_array_50_6_reload : out_array_49_6_reload);

assign select_ln39_29_fu_1644_p3 = ((icmp_ln39_38_fu_1470_p2[0:0] == 1'b1) ? out_array_48_6_reload : out_array_47_6_reload);

assign select_ln39_30_fu_1656_p3 = ((icmp_ln39_36_fu_1458_p2[0:0] == 1'b1) ? out_array_46_6_reload : out_array_45_6_reload);

assign select_ln39_31_fu_1668_p3 = ((icmp_ln39_34_fu_1446_p2[0:0] == 1'b1) ? out_array_44_6_reload : out_array_43_6_reload);

assign select_ln39_32_fu_1680_p3 = ((icmp_ln39_32_fu_1434_p2[0:0] == 1'b1) ? out_array_42_6_reload : out_array_41_6_reload);

assign select_ln39_33_fu_1692_p3 = ((icmp_ln39_30_fu_1422_p2[0:0] == 1'b1) ? out_array_40_6_reload : out_array_39_6_reload);

assign select_ln39_34_fu_1704_p3 = ((icmp_ln39_28_fu_1410_p2[0:0] == 1'b1) ? out_array_38_6_reload : out_array_37_6_reload);

assign select_ln39_35_fu_1716_p3 = ((icmp_ln39_26_fu_1398_p2[0:0] == 1'b1) ? out_array_36_6_reload : out_array_35_6_reload);

assign select_ln39_36_fu_1728_p3 = ((icmp_ln39_24_fu_1386_p2[0:0] == 1'b1) ? out_array_34_6_reload : out_array_33_6_reload);

assign select_ln39_37_fu_1740_p3 = ((icmp_ln39_fu_1374_p2[0:0] == 1'b1) ? out_array_32_6_reload : out_array_63_6_reload);

assign select_ln39_38_fu_1746_p3 = ((or_ln39_fu_1566_p2[0:0] == 1'b1) ? select_ln39_fu_1560_p3 : select_ln39_23_fu_1572_p3);

assign select_ln39_39_fu_1760_p3 = ((or_ln39_15_fu_1590_p2[0:0] == 1'b1) ? select_ln39_24_fu_1584_p3 : select_ln39_25_fu_1596_p3);

assign select_ln39_40_fu_1774_p3 = ((or_ln39_17_fu_1614_p2[0:0] == 1'b1) ? select_ln39_26_fu_1608_p3 : select_ln39_27_fu_1620_p3);

assign select_ln39_41_fu_1788_p3 = ((or_ln39_19_fu_1638_p2[0:0] == 1'b1) ? select_ln39_28_fu_1632_p3 : select_ln39_29_fu_1644_p3);

assign select_ln39_42_fu_1802_p3 = ((or_ln39_21_fu_1662_p2[0:0] == 1'b1) ? select_ln39_30_fu_1656_p3 : select_ln39_31_fu_1668_p3);

assign select_ln39_43_fu_1816_p3 = ((or_ln39_23_fu_1686_p2[0:0] == 1'b1) ? select_ln39_32_fu_1680_p3 : select_ln39_33_fu_1692_p3);

assign select_ln39_44_fu_1830_p3 = ((or_ln39_25_fu_1710_p2[0:0] == 1'b1) ? select_ln39_34_fu_1704_p3 : select_ln39_35_fu_1716_p3);

assign select_ln39_45_fu_1844_p3 = ((or_ln39_27_fu_1734_p2[0:0] == 1'b1) ? select_ln39_36_fu_1728_p3 : select_ln39_37_fu_1740_p3);

assign select_ln39_46_fu_1852_p3 = ((or_ln39_28_fu_1754_p2[0:0] == 1'b1) ? select_ln39_38_fu_1746_p3 : select_ln39_39_fu_1760_p3);

assign select_ln39_47_fu_1866_p3 = ((or_ln39_30_fu_1782_p2[0:0] == 1'b1) ? select_ln39_40_fu_1774_p3 : select_ln39_41_fu_1788_p3);

assign select_ln39_48_fu_1880_p3 = ((or_ln39_32_fu_1810_p2[0:0] == 1'b1) ? select_ln39_42_fu_1802_p3 : select_ln39_43_fu_1816_p3);

assign select_ln39_49_fu_1894_p3 = ((or_ln39_34_fu_1838_p2[0:0] == 1'b1) ? select_ln39_44_fu_1830_p3 : select_ln39_45_fu_1844_p3);

assign select_ln39_50_fu_1902_p3 = ((or_ln39_35_fu_1860_p2[0:0] == 1'b1) ? select_ln39_46_fu_1852_p3 : select_ln39_47_fu_1866_p3);

assign select_ln39_51_fu_1916_p3 = ((or_ln39_37_fu_1888_p2[0:0] == 1'b1) ? select_ln39_48_fu_1880_p3 : select_ln39_49_fu_1894_p3);

assign select_ln39_fu_1560_p3 = ((icmp_ln39_52_fu_1554_p2[0:0] == 1'b1) ? out_array_62_6_reload : out_array_61_6_reload);

assign tem2_fu_1929_p3 = ((or_ln39_38_reg_2667[0:0] == 1'b1) ? select_ln39_50_reg_2662 : select_ln39_51_reg_2672);

assign trunc_ln38_fu_1300_p1 = i_4_fu_284[4:0];

endmodule //eucHW_eucHW_Pipeline_VITIS_LOOP_34_24
