#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("A_0", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("A_1", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("A_2", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("A_3", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("A_4", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("A_5", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("A_6", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("A_7", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("A_8", 32, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("A_9", 32, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("A_10", 32, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("A_11", 32, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("A_12", 32, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("A_13", 32, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("A_14", 32, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("A_15", 32, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("B_0", 32, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("B_1", 32, hls_in, 17, "ap_none", "in_data", 1),
	Port_Property("B_2", 32, hls_in, 18, "ap_none", "in_data", 1),
	Port_Property("B_3", 32, hls_in, 19, "ap_none", "in_data", 1),
	Port_Property("B_4", 32, hls_in, 20, "ap_none", "in_data", 1),
	Port_Property("B_5", 32, hls_in, 21, "ap_none", "in_data", 1),
	Port_Property("B_6", 32, hls_in, 22, "ap_none", "in_data", 1),
	Port_Property("B_7", 32, hls_in, 23, "ap_none", "in_data", 1),
	Port_Property("B_8", 32, hls_in, 24, "ap_none", "in_data", 1),
	Port_Property("B_9", 32, hls_in, 25, "ap_none", "in_data", 1),
	Port_Property("B_10", 32, hls_in, 26, "ap_none", "in_data", 1),
	Port_Property("B_11", 32, hls_in, 27, "ap_none", "in_data", 1),
	Port_Property("B_12", 32, hls_in, 28, "ap_none", "in_data", 1),
	Port_Property("B_13", 32, hls_in, 29, "ap_none", "in_data", 1),
	Port_Property("B_14", 32, hls_in, 30, "ap_none", "in_data", 1),
	Port_Property("B_15", 32, hls_in, 31, "ap_none", "in_data", 1),
	Port_Property("C_i", 32, hls_in, 32, "ap_ovld", "in_data", 1),
	Port_Property("C_o", 32, hls_out, 32, "ap_ovld", "out_data", 1),
	Port_Property("C_o_ap_vld", 1, hls_out, 32, "ap_ovld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "eucDistHW";
