// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="eucHW_eucHW,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a12ti-csg325-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.006625,HLS_SYN_LAT=13,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=699,HLS_SYN_LUT=1840,HLS_VERSION=2021_1}" *)

module eucHW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A,
        B,
        C,
        C_ap_vld
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] A;
input  [63:0] B;
output  [31:0] C;
output   C_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg C_ap_vld;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [17:0] sext_ln19_2_fu_104_p1;
wire   [8:0] sub_ln19_1_fu_136_p2;
reg   [8:0] sub_ln19_1_reg_479;
wire   [8:0] sub_ln19_2_fu_170_p2;
reg   [8:0] sub_ln19_2_reg_484;
wire  signed [17:0] sext_ln19_11_fu_210_p1;
wire   [8:0] sub_ln19_4_fu_242_p2;
reg   [8:0] sub_ln19_4_reg_495;
wire  signed [17:0] sext_ln19_17_fu_282_p1;
wire   [8:0] sub_ln19_6_fu_314_p2;
reg   [8:0] sub_ln19_6_reg_506;
wire  signed [17:0] sext_ln19_23_fu_354_p1;
wire  signed [17:0] mul_ln19_fu_361_p2;
wire    ap_CS_fsm_state3;
wire  signed [17:0] mul_ln19_1_fu_370_p2;
wire  signed [17:0] mul_ln19_3_fu_379_p2;
wire  signed [17:0] mul_ln19_5_fu_388_p2;
wire   [19:0] result_2_fu_426_p2;
reg   [19:0] result_2_reg_537;
wire    ap_CS_fsm_state4;
wire   [15:0] grp_sqrt_fixed_32_32_s_fu_77_ap_return;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state14;
wire   [7:0] trunc_ln19_fu_82_p1;
wire   [7:0] trunc_ln19_1_fu_90_p1;
wire  signed [8:0] sext_ln19_fu_86_p1;
wire  signed [8:0] sext_ln19_1_fu_94_p1;
wire   [8:0] sub_ln19_fu_98_p2;
wire   [7:0] trunc_ln19_2_fu_108_p4;
wire   [7:0] trunc_ln19_3_fu_122_p4;
wire  signed [8:0] sext_ln19_3_fu_118_p1;
wire  signed [8:0] sext_ln19_4_fu_132_p1;
wire   [7:0] trunc_ln19_4_fu_142_p4;
wire   [7:0] trunc_ln19_5_fu_156_p4;
wire  signed [8:0] sext_ln19_6_fu_152_p1;
wire  signed [8:0] sext_ln19_7_fu_166_p1;
wire   [7:0] trunc_ln19_6_fu_176_p4;
wire   [7:0] trunc_ln19_7_fu_190_p4;
wire  signed [8:0] sext_ln19_9_fu_186_p1;
wire  signed [8:0] sext_ln19_10_fu_200_p1;
wire   [8:0] sub_ln19_3_fu_204_p2;
wire   [7:0] trunc_ln19_8_fu_214_p4;
wire   [7:0] trunc_ln19_9_fu_228_p4;
wire  signed [8:0] sext_ln19_12_fu_224_p1;
wire  signed [8:0] sext_ln19_13_fu_238_p1;
wire   [7:0] trunc_ln19_s_fu_248_p4;
wire   [7:0] trunc_ln19_10_fu_262_p4;
wire  signed [8:0] sext_ln19_15_fu_258_p1;
wire  signed [8:0] sext_ln19_16_fu_272_p1;
wire   [8:0] sub_ln19_5_fu_276_p2;
wire   [7:0] trunc_ln19_11_fu_286_p4;
wire   [7:0] trunc_ln19_12_fu_300_p4;
wire  signed [8:0] sext_ln19_18_fu_296_p1;
wire  signed [8:0] sext_ln19_19_fu_310_p1;
wire   [7:0] trunc_ln19_13_fu_320_p4;
wire   [7:0] trunc_ln19_14_fu_334_p4;
wire  signed [8:0] sext_ln19_21_fu_330_p1;
wire  signed [8:0] sext_ln19_22_fu_344_p1;
wire   [8:0] sub_ln19_7_fu_348_p2;
wire  signed [8:0] mul_ln19_fu_361_p0;
wire  signed [17:0] sext_ln19_5_fu_358_p1;
wire  signed [8:0] mul_ln19_fu_361_p1;
wire  signed [8:0] mul_ln19_1_fu_370_p0;
wire  signed [17:0] sext_ln19_8_fu_367_p1;
wire  signed [8:0] mul_ln19_1_fu_370_p1;
wire  signed [8:0] mul_ln19_3_fu_379_p0;
wire  signed [17:0] sext_ln19_14_fu_376_p1;
wire  signed [8:0] mul_ln19_3_fu_379_p1;
wire  signed [8:0] mul_ln19_5_fu_388_p0;
wire  signed [17:0] sext_ln19_20_fu_385_p1;
wire  signed [8:0] mul_ln19_5_fu_388_p1;
wire  signed [17:0] grp_fu_437_p3;
wire  signed [17:0] grp_fu_446_p3;
wire  signed [18:0] sext_ln19_25_fu_397_p1;
wire  signed [18:0] sext_ln19_24_fu_394_p1;
wire   [18:0] add_ln19_2_fu_400_p2;
wire  signed [17:0] grp_fu_455_p3;
wire  signed [17:0] grp_fu_464_p3;
wire  signed [18:0] sext_ln19_28_fu_413_p1;
wire  signed [18:0] sext_ln19_27_fu_410_p1;
wire   [18:0] add_ln19_5_fu_416_p2;
wire  signed [19:0] sext_ln19_29_fu_422_p1;
wire  signed [19:0] sext_ln19_26_fu_406_p1;
wire  signed [8:0] grp_fu_437_p0;
wire  signed [8:0] grp_fu_437_p1;
wire  signed [8:0] grp_fu_446_p0;
wire  signed [8:0] grp_fu_446_p1;
wire  signed [8:0] grp_fu_455_p0;
wire  signed [8:0] grp_fu_455_p1;
wire  signed [8:0] grp_fu_464_p0;
wire  signed [8:0] grp_fu_464_p1;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
end

eucHW_sqrt_fixed_32_32_s grp_sqrt_fixed_32_32_s_fu_77(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(result_2_reg_537),
    .ap_return(grp_sqrt_fixed_32_32_s_fu_77_ap_return)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U2(
    .din0(mul_ln19_fu_361_p0),
    .din1(mul_ln19_fu_361_p1),
    .dout(mul_ln19_fu_361_p2)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U3(
    .din0(mul_ln19_1_fu_370_p0),
    .din1(mul_ln19_1_fu_370_p1),
    .dout(mul_ln19_1_fu_370_p2)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U4(
    .din0(mul_ln19_3_fu_379_p0),
    .din1(mul_ln19_3_fu_379_p1),
    .dout(mul_ln19_3_fu_379_p2)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U5(
    .din0(mul_ln19_5_fu_388_p0),
    .din1(mul_ln19_5_fu_388_p1),
    .dout(mul_ln19_5_fu_388_p2)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_437_p0),
    .din1(grp_fu_437_p1),
    .din2(mul_ln19_fu_361_p2),
    .ce(1'b1),
    .dout(grp_fu_437_p3)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_446_p0),
    .din1(grp_fu_446_p1),
    .din2(mul_ln19_1_fu_370_p2),
    .ce(1'b1),
    .dout(grp_fu_446_p3)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_455_p0),
    .din1(grp_fu_455_p1),
    .din2(mul_ln19_3_fu_379_p2),
    .ce(1'b1),
    .dout(grp_fu_455_p3)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_464_p0),
    .din1(grp_fu_464_p1),
    .din2(mul_ln19_5_fu_388_p2),
    .ce(1'b1),
    .dout(grp_fu_464_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        result_2_reg_537 <= result_2_fu_426_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sub_ln19_1_reg_479 <= sub_ln19_1_fu_136_p2;
        sub_ln19_2_reg_484 <= sub_ln19_2_fu_170_p2;
        sub_ln19_4_reg_495 <= sub_ln19_4_fu_242_p2;
        sub_ln19_6_reg_506 <= sub_ln19_6_fu_314_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        C_ap_vld = 1'b1;
    end else begin
        C_ap_vld = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C = grp_sqrt_fixed_32_32_s_fu_77_ap_return;

assign add_ln19_2_fu_400_p2 = ($signed(sext_ln19_25_fu_397_p1) + $signed(sext_ln19_24_fu_394_p1));

assign add_ln19_5_fu_416_p2 = ($signed(sext_ln19_28_fu_413_p1) + $signed(sext_ln19_27_fu_410_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_fu_437_p0 = sext_ln19_2_fu_104_p1;

assign grp_fu_437_p1 = sext_ln19_2_fu_104_p1;

assign grp_fu_446_p0 = sext_ln19_11_fu_210_p1;

assign grp_fu_446_p1 = sext_ln19_11_fu_210_p1;

assign grp_fu_455_p0 = sext_ln19_17_fu_282_p1;

assign grp_fu_455_p1 = sext_ln19_17_fu_282_p1;

assign grp_fu_464_p0 = sext_ln19_23_fu_354_p1;

assign grp_fu_464_p1 = sext_ln19_23_fu_354_p1;

assign mul_ln19_1_fu_370_p0 = sext_ln19_8_fu_367_p1;

assign mul_ln19_1_fu_370_p1 = sext_ln19_8_fu_367_p1;

assign mul_ln19_3_fu_379_p0 = sext_ln19_14_fu_376_p1;

assign mul_ln19_3_fu_379_p1 = sext_ln19_14_fu_376_p1;

assign mul_ln19_5_fu_388_p0 = sext_ln19_20_fu_385_p1;

assign mul_ln19_5_fu_388_p1 = sext_ln19_20_fu_385_p1;

assign mul_ln19_fu_361_p0 = sext_ln19_5_fu_358_p1;

assign mul_ln19_fu_361_p1 = sext_ln19_5_fu_358_p1;

assign result_2_fu_426_p2 = ($signed(sext_ln19_29_fu_422_p1) + $signed(sext_ln19_26_fu_406_p1));

assign sext_ln19_10_fu_200_p1 = $signed(trunc_ln19_7_fu_190_p4);

assign sext_ln19_11_fu_210_p1 = $signed(sub_ln19_3_fu_204_p2);

assign sext_ln19_12_fu_224_p1 = $signed(trunc_ln19_8_fu_214_p4);

assign sext_ln19_13_fu_238_p1 = $signed(trunc_ln19_9_fu_228_p4);

assign sext_ln19_14_fu_376_p1 = $signed(sub_ln19_4_reg_495);

assign sext_ln19_15_fu_258_p1 = $signed(trunc_ln19_s_fu_248_p4);

assign sext_ln19_16_fu_272_p1 = $signed(trunc_ln19_10_fu_262_p4);

assign sext_ln19_17_fu_282_p1 = $signed(sub_ln19_5_fu_276_p2);

assign sext_ln19_18_fu_296_p1 = $signed(trunc_ln19_11_fu_286_p4);

assign sext_ln19_19_fu_310_p1 = $signed(trunc_ln19_12_fu_300_p4);

assign sext_ln19_1_fu_94_p1 = $signed(trunc_ln19_1_fu_90_p1);

assign sext_ln19_20_fu_385_p1 = $signed(sub_ln19_6_reg_506);

assign sext_ln19_21_fu_330_p1 = $signed(trunc_ln19_13_fu_320_p4);

assign sext_ln19_22_fu_344_p1 = $signed(trunc_ln19_14_fu_334_p4);

assign sext_ln19_23_fu_354_p1 = $signed(sub_ln19_7_fu_348_p2);

assign sext_ln19_24_fu_394_p1 = grp_fu_437_p3;

assign sext_ln19_25_fu_397_p1 = grp_fu_446_p3;

assign sext_ln19_26_fu_406_p1 = $signed(add_ln19_2_fu_400_p2);

assign sext_ln19_27_fu_410_p1 = grp_fu_455_p3;

assign sext_ln19_28_fu_413_p1 = grp_fu_464_p3;

assign sext_ln19_29_fu_422_p1 = $signed(add_ln19_5_fu_416_p2);

assign sext_ln19_2_fu_104_p1 = $signed(sub_ln19_fu_98_p2);

assign sext_ln19_3_fu_118_p1 = $signed(trunc_ln19_2_fu_108_p4);

assign sext_ln19_4_fu_132_p1 = $signed(trunc_ln19_3_fu_122_p4);

assign sext_ln19_5_fu_358_p1 = $signed(sub_ln19_1_reg_479);

assign sext_ln19_6_fu_152_p1 = $signed(trunc_ln19_4_fu_142_p4);

assign sext_ln19_7_fu_166_p1 = $signed(trunc_ln19_5_fu_156_p4);

assign sext_ln19_8_fu_367_p1 = $signed(sub_ln19_2_reg_484);

assign sext_ln19_9_fu_186_p1 = $signed(trunc_ln19_6_fu_176_p4);

assign sext_ln19_fu_86_p1 = $signed(trunc_ln19_fu_82_p1);

assign sub_ln19_1_fu_136_p2 = ($signed(sext_ln19_3_fu_118_p1) - $signed(sext_ln19_4_fu_132_p1));

assign sub_ln19_2_fu_170_p2 = ($signed(sext_ln19_6_fu_152_p1) - $signed(sext_ln19_7_fu_166_p1));

assign sub_ln19_3_fu_204_p2 = ($signed(sext_ln19_9_fu_186_p1) - $signed(sext_ln19_10_fu_200_p1));

assign sub_ln19_4_fu_242_p2 = ($signed(sext_ln19_12_fu_224_p1) - $signed(sext_ln19_13_fu_238_p1));

assign sub_ln19_5_fu_276_p2 = ($signed(sext_ln19_15_fu_258_p1) - $signed(sext_ln19_16_fu_272_p1));

assign sub_ln19_6_fu_314_p2 = ($signed(sext_ln19_18_fu_296_p1) - $signed(sext_ln19_19_fu_310_p1));

assign sub_ln19_7_fu_348_p2 = ($signed(sext_ln19_21_fu_330_p1) - $signed(sext_ln19_22_fu_344_p1));

assign sub_ln19_fu_98_p2 = ($signed(sext_ln19_fu_86_p1) - $signed(sext_ln19_1_fu_94_p1));

assign trunc_ln19_10_fu_262_p4 = {{B[47:40]}};

assign trunc_ln19_11_fu_286_p4 = {{A[55:48]}};

assign trunc_ln19_12_fu_300_p4 = {{B[55:48]}};

assign trunc_ln19_13_fu_320_p4 = {{A[63:56]}};

assign trunc_ln19_14_fu_334_p4 = {{B[63:56]}};

assign trunc_ln19_1_fu_90_p1 = B[7:0];

assign trunc_ln19_2_fu_108_p4 = {{A[15:8]}};

assign trunc_ln19_3_fu_122_p4 = {{B[15:8]}};

assign trunc_ln19_4_fu_142_p4 = {{A[23:16]}};

assign trunc_ln19_5_fu_156_p4 = {{B[23:16]}};

assign trunc_ln19_6_fu_176_p4 = {{A[31:24]}};

assign trunc_ln19_7_fu_190_p4 = {{B[31:24]}};

assign trunc_ln19_8_fu_214_p4 = {{A[39:32]}};

assign trunc_ln19_9_fu_228_p4 = {{B[39:32]}};

assign trunc_ln19_fu_82_p1 = A[7:0];

assign trunc_ln19_s_fu_248_p4 = {{A[47:40]}};

endmodule //eucHW
