// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="eucHW_eucHW,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a12ti-csg325-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.006625,HLS_SYN_LAT=14,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=779,HLS_SYN_LUT=2283,HLS_VERSION=2021_1}" *)

module eucHW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A,
        B,
        C,
        C_ap_vld
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] A;
input  [127:0] B;
output  [31:0] C;
output   C_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg C_ap_vld;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [17:0] sext_ln21_2_fu_136_p1;
wire   [8:0] sub_ln21_1_fu_168_p2;
reg   [8:0] sub_ln21_1_reg_921;
wire   [8:0] sub_ln21_2_fu_202_p2;
reg   [8:0] sub_ln21_2_reg_926;
wire  signed [17:0] sext_ln21_11_fu_242_p1;
wire   [8:0] sub_ln21_4_fu_274_p2;
reg   [8:0] sub_ln21_4_reg_937;
wire  signed [17:0] sext_ln21_17_fu_314_p1;
wire   [8:0] sub_ln21_6_fu_346_p2;
reg   [8:0] sub_ln21_6_reg_948;
wire  signed [17:0] sext_ln21_23_fu_386_p1;
wire   [8:0] sub_ln21_8_fu_418_p2;
reg   [8:0] sub_ln21_8_reg_959;
wire  signed [17:0] sext_ln21_29_fu_458_p1;
wire   [8:0] sub_ln21_10_fu_490_p2;
reg   [8:0] sub_ln21_10_reg_970;
wire  signed [17:0] sext_ln21_35_fu_530_p1;
wire   [8:0] sub_ln21_12_fu_562_p2;
reg   [8:0] sub_ln21_12_reg_981;
wire  signed [17:0] sext_ln21_41_fu_602_p1;
wire   [8:0] sub_ln21_14_fu_634_p2;
reg   [8:0] sub_ln21_14_reg_992;
wire  signed [17:0] sext_ln21_47_fu_674_p1;
wire  signed [17:0] mul_ln21_fu_681_p2;
wire    ap_CS_fsm_state3;
wire  signed [17:0] mul_ln21_1_fu_690_p2;
wire  signed [17:0] mul_ln21_3_fu_699_p2;
wire  signed [17:0] mul_ln21_5_fu_708_p2;
wire  signed [17:0] mul_ln21_7_fu_717_p2;
wire  signed [17:0] mul_ln21_9_fu_726_p2;
wire  signed [17:0] mul_ln21_11_fu_735_p2;
wire  signed [17:0] mul_ln21_13_fu_744_p2;
wire   [19:0] add_ln21_6_fu_782_p2;
reg   [19:0] add_ln21_6_reg_1043;
wire    ap_CS_fsm_state4;
wire   [19:0] add_ln21_13_fu_820_p2;
reg   [19:0] add_ln21_13_reg_1048;
wire   [20:0] result_2_fu_832_p2;
reg   [20:0] result_2_reg_1053;
wire    ap_CS_fsm_state5;
wire   [15:0] grp_sqrt_fixed_32_32_s_fu_109_ap_return;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state15;
wire   [7:0] trunc_ln21_fu_114_p1;
wire   [7:0] trunc_ln21_1_fu_122_p1;
wire  signed [8:0] sext_ln21_fu_118_p1;
wire  signed [8:0] sext_ln21_1_fu_126_p1;
wire   [8:0] sub_ln21_fu_130_p2;
wire   [7:0] trunc_ln21_2_fu_140_p4;
wire   [7:0] trunc_ln21_3_fu_154_p4;
wire  signed [8:0] sext_ln21_3_fu_150_p1;
wire  signed [8:0] sext_ln21_4_fu_164_p1;
wire   [7:0] trunc_ln21_4_fu_174_p4;
wire   [7:0] trunc_ln21_5_fu_188_p4;
wire  signed [8:0] sext_ln21_6_fu_184_p1;
wire  signed [8:0] sext_ln21_7_fu_198_p1;
wire   [7:0] trunc_ln21_6_fu_208_p4;
wire   [7:0] trunc_ln21_7_fu_222_p4;
wire  signed [8:0] sext_ln21_9_fu_218_p1;
wire  signed [8:0] sext_ln21_10_fu_232_p1;
wire   [8:0] sub_ln21_3_fu_236_p2;
wire   [7:0] trunc_ln21_8_fu_246_p4;
wire   [7:0] trunc_ln21_9_fu_260_p4;
wire  signed [8:0] sext_ln21_12_fu_256_p1;
wire  signed [8:0] sext_ln21_13_fu_270_p1;
wire   [7:0] trunc_ln21_s_fu_280_p4;
wire   [7:0] trunc_ln21_10_fu_294_p4;
wire  signed [8:0] sext_ln21_15_fu_290_p1;
wire  signed [8:0] sext_ln21_16_fu_304_p1;
wire   [8:0] sub_ln21_5_fu_308_p2;
wire   [7:0] trunc_ln21_11_fu_318_p4;
wire   [7:0] trunc_ln21_12_fu_332_p4;
wire  signed [8:0] sext_ln21_18_fu_328_p1;
wire  signed [8:0] sext_ln21_19_fu_342_p1;
wire   [7:0] trunc_ln21_13_fu_352_p4;
wire   [7:0] trunc_ln21_14_fu_366_p4;
wire  signed [8:0] sext_ln21_21_fu_362_p1;
wire  signed [8:0] sext_ln21_22_fu_376_p1;
wire   [8:0] sub_ln21_7_fu_380_p2;
wire   [7:0] trunc_ln21_15_fu_390_p4;
wire   [7:0] trunc_ln21_16_fu_404_p4;
wire  signed [8:0] sext_ln21_24_fu_400_p1;
wire  signed [8:0] sext_ln21_25_fu_414_p1;
wire   [7:0] trunc_ln21_17_fu_424_p4;
wire   [7:0] trunc_ln21_18_fu_438_p4;
wire  signed [8:0] sext_ln21_27_fu_434_p1;
wire  signed [8:0] sext_ln21_28_fu_448_p1;
wire   [8:0] sub_ln21_9_fu_452_p2;
wire   [7:0] trunc_ln21_19_fu_462_p4;
wire   [7:0] trunc_ln21_20_fu_476_p4;
wire  signed [8:0] sext_ln21_30_fu_472_p1;
wire  signed [8:0] sext_ln21_31_fu_486_p1;
wire   [7:0] trunc_ln21_21_fu_496_p4;
wire   [7:0] trunc_ln21_22_fu_510_p4;
wire  signed [8:0] sext_ln21_33_fu_506_p1;
wire  signed [8:0] sext_ln21_34_fu_520_p1;
wire   [8:0] sub_ln21_11_fu_524_p2;
wire   [7:0] trunc_ln21_23_fu_534_p4;
wire   [7:0] trunc_ln21_24_fu_548_p4;
wire  signed [8:0] sext_ln21_36_fu_544_p1;
wire  signed [8:0] sext_ln21_37_fu_558_p1;
wire   [7:0] trunc_ln21_25_fu_568_p4;
wire   [7:0] trunc_ln21_26_fu_582_p4;
wire  signed [8:0] sext_ln21_39_fu_578_p1;
wire  signed [8:0] sext_ln21_40_fu_592_p1;
wire   [8:0] sub_ln21_13_fu_596_p2;
wire   [7:0] trunc_ln21_27_fu_606_p4;
wire   [7:0] trunc_ln21_28_fu_620_p4;
wire  signed [8:0] sext_ln21_42_fu_616_p1;
wire  signed [8:0] sext_ln21_43_fu_630_p1;
wire   [7:0] trunc_ln21_29_fu_640_p4;
wire   [7:0] trunc_ln21_30_fu_654_p4;
wire  signed [8:0] sext_ln21_45_fu_650_p1;
wire  signed [8:0] sext_ln21_46_fu_664_p1;
wire   [8:0] sub_ln21_15_fu_668_p2;
wire  signed [8:0] mul_ln21_fu_681_p0;
wire  signed [17:0] sext_ln21_5_fu_678_p1;
wire  signed [8:0] mul_ln21_fu_681_p1;
wire  signed [8:0] mul_ln21_1_fu_690_p0;
wire  signed [17:0] sext_ln21_8_fu_687_p1;
wire  signed [8:0] mul_ln21_1_fu_690_p1;
wire  signed [8:0] mul_ln21_3_fu_699_p0;
wire  signed [17:0] sext_ln21_14_fu_696_p1;
wire  signed [8:0] mul_ln21_3_fu_699_p1;
wire  signed [8:0] mul_ln21_5_fu_708_p0;
wire  signed [17:0] sext_ln21_20_fu_705_p1;
wire  signed [8:0] mul_ln21_5_fu_708_p1;
wire  signed [8:0] mul_ln21_7_fu_717_p0;
wire  signed [17:0] sext_ln21_26_fu_714_p1;
wire  signed [8:0] mul_ln21_7_fu_717_p1;
wire  signed [8:0] mul_ln21_9_fu_726_p0;
wire  signed [17:0] sext_ln21_32_fu_723_p1;
wire  signed [8:0] mul_ln21_9_fu_726_p1;
wire  signed [8:0] mul_ln21_11_fu_735_p0;
wire  signed [17:0] sext_ln21_38_fu_732_p1;
wire  signed [8:0] mul_ln21_11_fu_735_p1;
wire  signed [8:0] mul_ln21_13_fu_744_p0;
wire  signed [17:0] sext_ln21_44_fu_741_p1;
wire  signed [8:0] mul_ln21_13_fu_744_p1;
wire  signed [17:0] grp_fu_843_p3;
wire  signed [17:0] grp_fu_852_p3;
wire  signed [18:0] sext_ln21_49_fu_753_p1;
wire  signed [18:0] sext_ln21_48_fu_750_p1;
wire   [18:0] add_ln21_2_fu_756_p2;
wire  signed [17:0] grp_fu_861_p3;
wire  signed [17:0] grp_fu_870_p3;
wire  signed [18:0] sext_ln21_52_fu_769_p1;
wire  signed [18:0] sext_ln21_51_fu_766_p1;
wire   [18:0] add_ln21_5_fu_772_p2;
wire  signed [19:0] sext_ln21_53_fu_778_p1;
wire  signed [19:0] sext_ln21_50_fu_762_p1;
wire  signed [17:0] grp_fu_879_p3;
wire  signed [17:0] grp_fu_888_p3;
wire  signed [18:0] sext_ln21_56_fu_791_p1;
wire  signed [18:0] sext_ln21_55_fu_788_p1;
wire   [18:0] add_ln21_9_fu_794_p2;
wire  signed [17:0] grp_fu_897_p3;
wire  signed [17:0] grp_fu_906_p3;
wire  signed [18:0] sext_ln21_59_fu_807_p1;
wire  signed [18:0] sext_ln21_58_fu_804_p1;
wire   [18:0] add_ln21_12_fu_810_p2;
wire  signed [19:0] sext_ln21_60_fu_816_p1;
wire  signed [19:0] sext_ln21_57_fu_800_p1;
wire  signed [20:0] sext_ln21_61_fu_829_p1;
wire  signed [20:0] sext_ln21_54_fu_826_p1;
wire  signed [8:0] grp_fu_843_p0;
wire  signed [8:0] grp_fu_843_p1;
wire  signed [8:0] grp_fu_852_p0;
wire  signed [8:0] grp_fu_852_p1;
wire  signed [8:0] grp_fu_861_p0;
wire  signed [8:0] grp_fu_861_p1;
wire  signed [8:0] grp_fu_870_p0;
wire  signed [8:0] grp_fu_870_p1;
wire  signed [8:0] grp_fu_879_p0;
wire  signed [8:0] grp_fu_879_p1;
wire  signed [8:0] grp_fu_888_p0;
wire  signed [8:0] grp_fu_888_p1;
wire  signed [8:0] grp_fu_897_p0;
wire  signed [8:0] grp_fu_897_p1;
wire  signed [8:0] grp_fu_906_p0;
wire  signed [8:0] grp_fu_906_p1;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
end

eucHW_sqrt_fixed_32_32_s grp_sqrt_fixed_32_32_s_fu_109(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(result_2_reg_1053),
    .ap_return(grp_sqrt_fixed_32_32_s_fu_109_ap_return)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U2(
    .din0(mul_ln21_fu_681_p0),
    .din1(mul_ln21_fu_681_p1),
    .dout(mul_ln21_fu_681_p2)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U3(
    .din0(mul_ln21_1_fu_690_p0),
    .din1(mul_ln21_1_fu_690_p1),
    .dout(mul_ln21_1_fu_690_p2)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U4(
    .din0(mul_ln21_3_fu_699_p0),
    .din1(mul_ln21_3_fu_699_p1),
    .dout(mul_ln21_3_fu_699_p2)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U5(
    .din0(mul_ln21_5_fu_708_p0),
    .din1(mul_ln21_5_fu_708_p1),
    .dout(mul_ln21_5_fu_708_p2)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U6(
    .din0(mul_ln21_7_fu_717_p0),
    .din1(mul_ln21_7_fu_717_p1),
    .dout(mul_ln21_7_fu_717_p2)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U7(
    .din0(mul_ln21_9_fu_726_p0),
    .din1(mul_ln21_9_fu_726_p1),
    .dout(mul_ln21_9_fu_726_p2)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U8(
    .din0(mul_ln21_11_fu_735_p0),
    .din1(mul_ln21_11_fu_735_p1),
    .dout(mul_ln21_11_fu_735_p2)
);

eucHW_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U9(
    .din0(mul_ln21_13_fu_744_p0),
    .din1(mul_ln21_13_fu_744_p1),
    .dout(mul_ln21_13_fu_744_p2)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_843_p0),
    .din1(grp_fu_843_p1),
    .din2(mul_ln21_fu_681_p2),
    .ce(1'b1),
    .dout(grp_fu_843_p3)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_852_p0),
    .din1(grp_fu_852_p1),
    .din2(mul_ln21_1_fu_690_p2),
    .ce(1'b1),
    .dout(grp_fu_852_p3)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_861_p0),
    .din1(grp_fu_861_p1),
    .din2(mul_ln21_3_fu_699_p2),
    .ce(1'b1),
    .dout(grp_fu_861_p3)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_870_p0),
    .din1(grp_fu_870_p1),
    .din2(mul_ln21_5_fu_708_p2),
    .ce(1'b1),
    .dout(grp_fu_870_p3)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_879_p0),
    .din1(grp_fu_879_p1),
    .din2(mul_ln21_7_fu_717_p2),
    .ce(1'b1),
    .dout(grp_fu_879_p3)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_888_p0),
    .din1(grp_fu_888_p1),
    .din2(mul_ln21_9_fu_726_p2),
    .ce(1'b1),
    .dout(grp_fu_888_p3)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_897_p0),
    .din1(grp_fu_897_p1),
    .din2(mul_ln21_11_fu_735_p2),
    .ce(1'b1),
    .dout(grp_fu_897_p3)
);

eucHW_mac_muladd_9s_9s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_9s_9s_18s_18_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_906_p0),
    .din1(grp_fu_906_p1),
    .din2(mul_ln21_13_fu_744_p2),
    .ce(1'b1),
    .dout(grp_fu_906_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln21_13_reg_1048 <= add_ln21_13_fu_820_p2;
        add_ln21_6_reg_1043 <= add_ln21_6_fu_782_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        result_2_reg_1053 <= result_2_fu_832_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sub_ln21_10_reg_970 <= sub_ln21_10_fu_490_p2;
        sub_ln21_12_reg_981 <= sub_ln21_12_fu_562_p2;
        sub_ln21_14_reg_992 <= sub_ln21_14_fu_634_p2;
        sub_ln21_1_reg_921 <= sub_ln21_1_fu_168_p2;
        sub_ln21_2_reg_926 <= sub_ln21_2_fu_202_p2;
        sub_ln21_4_reg_937 <= sub_ln21_4_fu_274_p2;
        sub_ln21_6_reg_948 <= sub_ln21_6_fu_346_p2;
        sub_ln21_8_reg_959 <= sub_ln21_8_fu_418_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        C_ap_vld = 1'b1;
    end else begin
        C_ap_vld = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C = grp_sqrt_fixed_32_32_s_fu_109_ap_return;

assign add_ln21_12_fu_810_p2 = ($signed(sext_ln21_59_fu_807_p1) + $signed(sext_ln21_58_fu_804_p1));

assign add_ln21_13_fu_820_p2 = ($signed(sext_ln21_60_fu_816_p1) + $signed(sext_ln21_57_fu_800_p1));

assign add_ln21_2_fu_756_p2 = ($signed(sext_ln21_49_fu_753_p1) + $signed(sext_ln21_48_fu_750_p1));

assign add_ln21_5_fu_772_p2 = ($signed(sext_ln21_52_fu_769_p1) + $signed(sext_ln21_51_fu_766_p1));

assign add_ln21_6_fu_782_p2 = ($signed(sext_ln21_53_fu_778_p1) + $signed(sext_ln21_50_fu_762_p1));

assign add_ln21_9_fu_794_p2 = ($signed(sext_ln21_56_fu_791_p1) + $signed(sext_ln21_55_fu_788_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign grp_fu_843_p0 = sext_ln21_2_fu_136_p1;

assign grp_fu_843_p1 = sext_ln21_2_fu_136_p1;

assign grp_fu_852_p0 = sext_ln21_11_fu_242_p1;

assign grp_fu_852_p1 = sext_ln21_11_fu_242_p1;

assign grp_fu_861_p0 = sext_ln21_17_fu_314_p1;

assign grp_fu_861_p1 = sext_ln21_17_fu_314_p1;

assign grp_fu_870_p0 = sext_ln21_23_fu_386_p1;

assign grp_fu_870_p1 = sext_ln21_23_fu_386_p1;

assign grp_fu_879_p0 = sext_ln21_29_fu_458_p1;

assign grp_fu_879_p1 = sext_ln21_29_fu_458_p1;

assign grp_fu_888_p0 = sext_ln21_35_fu_530_p1;

assign grp_fu_888_p1 = sext_ln21_35_fu_530_p1;

assign grp_fu_897_p0 = sext_ln21_41_fu_602_p1;

assign grp_fu_897_p1 = sext_ln21_41_fu_602_p1;

assign grp_fu_906_p0 = sext_ln21_47_fu_674_p1;

assign grp_fu_906_p1 = sext_ln21_47_fu_674_p1;

assign mul_ln21_11_fu_735_p0 = sext_ln21_38_fu_732_p1;

assign mul_ln21_11_fu_735_p1 = sext_ln21_38_fu_732_p1;

assign mul_ln21_13_fu_744_p0 = sext_ln21_44_fu_741_p1;

assign mul_ln21_13_fu_744_p1 = sext_ln21_44_fu_741_p1;

assign mul_ln21_1_fu_690_p0 = sext_ln21_8_fu_687_p1;

assign mul_ln21_1_fu_690_p1 = sext_ln21_8_fu_687_p1;

assign mul_ln21_3_fu_699_p0 = sext_ln21_14_fu_696_p1;

assign mul_ln21_3_fu_699_p1 = sext_ln21_14_fu_696_p1;

assign mul_ln21_5_fu_708_p0 = sext_ln21_20_fu_705_p1;

assign mul_ln21_5_fu_708_p1 = sext_ln21_20_fu_705_p1;

assign mul_ln21_7_fu_717_p0 = sext_ln21_26_fu_714_p1;

assign mul_ln21_7_fu_717_p1 = sext_ln21_26_fu_714_p1;

assign mul_ln21_9_fu_726_p0 = sext_ln21_32_fu_723_p1;

assign mul_ln21_9_fu_726_p1 = sext_ln21_32_fu_723_p1;

assign mul_ln21_fu_681_p0 = sext_ln21_5_fu_678_p1;

assign mul_ln21_fu_681_p1 = sext_ln21_5_fu_678_p1;

assign result_2_fu_832_p2 = ($signed(sext_ln21_61_fu_829_p1) + $signed(sext_ln21_54_fu_826_p1));

assign sext_ln21_10_fu_232_p1 = $signed(trunc_ln21_7_fu_222_p4);

assign sext_ln21_11_fu_242_p1 = $signed(sub_ln21_3_fu_236_p2);

assign sext_ln21_12_fu_256_p1 = $signed(trunc_ln21_8_fu_246_p4);

assign sext_ln21_13_fu_270_p1 = $signed(trunc_ln21_9_fu_260_p4);

assign sext_ln21_14_fu_696_p1 = $signed(sub_ln21_4_reg_937);

assign sext_ln21_15_fu_290_p1 = $signed(trunc_ln21_s_fu_280_p4);

assign sext_ln21_16_fu_304_p1 = $signed(trunc_ln21_10_fu_294_p4);

assign sext_ln21_17_fu_314_p1 = $signed(sub_ln21_5_fu_308_p2);

assign sext_ln21_18_fu_328_p1 = $signed(trunc_ln21_11_fu_318_p4);

assign sext_ln21_19_fu_342_p1 = $signed(trunc_ln21_12_fu_332_p4);

assign sext_ln21_1_fu_126_p1 = $signed(trunc_ln21_1_fu_122_p1);

assign sext_ln21_20_fu_705_p1 = $signed(sub_ln21_6_reg_948);

assign sext_ln21_21_fu_362_p1 = $signed(trunc_ln21_13_fu_352_p4);

assign sext_ln21_22_fu_376_p1 = $signed(trunc_ln21_14_fu_366_p4);

assign sext_ln21_23_fu_386_p1 = $signed(sub_ln21_7_fu_380_p2);

assign sext_ln21_24_fu_400_p1 = $signed(trunc_ln21_15_fu_390_p4);

assign sext_ln21_25_fu_414_p1 = $signed(trunc_ln21_16_fu_404_p4);

assign sext_ln21_26_fu_714_p1 = $signed(sub_ln21_8_reg_959);

assign sext_ln21_27_fu_434_p1 = $signed(trunc_ln21_17_fu_424_p4);

assign sext_ln21_28_fu_448_p1 = $signed(trunc_ln21_18_fu_438_p4);

assign sext_ln21_29_fu_458_p1 = $signed(sub_ln21_9_fu_452_p2);

assign sext_ln21_2_fu_136_p1 = $signed(sub_ln21_fu_130_p2);

assign sext_ln21_30_fu_472_p1 = $signed(trunc_ln21_19_fu_462_p4);

assign sext_ln21_31_fu_486_p1 = $signed(trunc_ln21_20_fu_476_p4);

assign sext_ln21_32_fu_723_p1 = $signed(sub_ln21_10_reg_970);

assign sext_ln21_33_fu_506_p1 = $signed(trunc_ln21_21_fu_496_p4);

assign sext_ln21_34_fu_520_p1 = $signed(trunc_ln21_22_fu_510_p4);

assign sext_ln21_35_fu_530_p1 = $signed(sub_ln21_11_fu_524_p2);

assign sext_ln21_36_fu_544_p1 = $signed(trunc_ln21_23_fu_534_p4);

assign sext_ln21_37_fu_558_p1 = $signed(trunc_ln21_24_fu_548_p4);

assign sext_ln21_38_fu_732_p1 = $signed(sub_ln21_12_reg_981);

assign sext_ln21_39_fu_578_p1 = $signed(trunc_ln21_25_fu_568_p4);

assign sext_ln21_3_fu_150_p1 = $signed(trunc_ln21_2_fu_140_p4);

assign sext_ln21_40_fu_592_p1 = $signed(trunc_ln21_26_fu_582_p4);

assign sext_ln21_41_fu_602_p1 = $signed(sub_ln21_13_fu_596_p2);

assign sext_ln21_42_fu_616_p1 = $signed(trunc_ln21_27_fu_606_p4);

assign sext_ln21_43_fu_630_p1 = $signed(trunc_ln21_28_fu_620_p4);

assign sext_ln21_44_fu_741_p1 = $signed(sub_ln21_14_reg_992);

assign sext_ln21_45_fu_650_p1 = $signed(trunc_ln21_29_fu_640_p4);

assign sext_ln21_46_fu_664_p1 = $signed(trunc_ln21_30_fu_654_p4);

assign sext_ln21_47_fu_674_p1 = $signed(sub_ln21_15_fu_668_p2);

assign sext_ln21_48_fu_750_p1 = grp_fu_843_p3;

assign sext_ln21_49_fu_753_p1 = grp_fu_852_p3;

assign sext_ln21_4_fu_164_p1 = $signed(trunc_ln21_3_fu_154_p4);

assign sext_ln21_50_fu_762_p1 = $signed(add_ln21_2_fu_756_p2);

assign sext_ln21_51_fu_766_p1 = grp_fu_861_p3;

assign sext_ln21_52_fu_769_p1 = grp_fu_870_p3;

assign sext_ln21_53_fu_778_p1 = $signed(add_ln21_5_fu_772_p2);

assign sext_ln21_54_fu_826_p1 = $signed(add_ln21_6_reg_1043);

assign sext_ln21_55_fu_788_p1 = grp_fu_879_p3;

assign sext_ln21_56_fu_791_p1 = grp_fu_888_p3;

assign sext_ln21_57_fu_800_p1 = $signed(add_ln21_9_fu_794_p2);

assign sext_ln21_58_fu_804_p1 = grp_fu_897_p3;

assign sext_ln21_59_fu_807_p1 = grp_fu_906_p3;

assign sext_ln21_5_fu_678_p1 = $signed(sub_ln21_1_reg_921);

assign sext_ln21_60_fu_816_p1 = $signed(add_ln21_12_fu_810_p2);

assign sext_ln21_61_fu_829_p1 = $signed(add_ln21_13_reg_1048);

assign sext_ln21_6_fu_184_p1 = $signed(trunc_ln21_4_fu_174_p4);

assign sext_ln21_7_fu_198_p1 = $signed(trunc_ln21_5_fu_188_p4);

assign sext_ln21_8_fu_687_p1 = $signed(sub_ln21_2_reg_926);

assign sext_ln21_9_fu_218_p1 = $signed(trunc_ln21_6_fu_208_p4);

assign sext_ln21_fu_118_p1 = $signed(trunc_ln21_fu_114_p1);

assign sub_ln21_10_fu_490_p2 = ($signed(sext_ln21_30_fu_472_p1) - $signed(sext_ln21_31_fu_486_p1));

assign sub_ln21_11_fu_524_p2 = ($signed(sext_ln21_33_fu_506_p1) - $signed(sext_ln21_34_fu_520_p1));

assign sub_ln21_12_fu_562_p2 = ($signed(sext_ln21_36_fu_544_p1) - $signed(sext_ln21_37_fu_558_p1));

assign sub_ln21_13_fu_596_p2 = ($signed(sext_ln21_39_fu_578_p1) - $signed(sext_ln21_40_fu_592_p1));

assign sub_ln21_14_fu_634_p2 = ($signed(sext_ln21_42_fu_616_p1) - $signed(sext_ln21_43_fu_630_p1));

assign sub_ln21_15_fu_668_p2 = ($signed(sext_ln21_45_fu_650_p1) - $signed(sext_ln21_46_fu_664_p1));

assign sub_ln21_1_fu_168_p2 = ($signed(sext_ln21_3_fu_150_p1) - $signed(sext_ln21_4_fu_164_p1));

assign sub_ln21_2_fu_202_p2 = ($signed(sext_ln21_6_fu_184_p1) - $signed(sext_ln21_7_fu_198_p1));

assign sub_ln21_3_fu_236_p2 = ($signed(sext_ln21_9_fu_218_p1) - $signed(sext_ln21_10_fu_232_p1));

assign sub_ln21_4_fu_274_p2 = ($signed(sext_ln21_12_fu_256_p1) - $signed(sext_ln21_13_fu_270_p1));

assign sub_ln21_5_fu_308_p2 = ($signed(sext_ln21_15_fu_290_p1) - $signed(sext_ln21_16_fu_304_p1));

assign sub_ln21_6_fu_346_p2 = ($signed(sext_ln21_18_fu_328_p1) - $signed(sext_ln21_19_fu_342_p1));

assign sub_ln21_7_fu_380_p2 = ($signed(sext_ln21_21_fu_362_p1) - $signed(sext_ln21_22_fu_376_p1));

assign sub_ln21_8_fu_418_p2 = ($signed(sext_ln21_24_fu_400_p1) - $signed(sext_ln21_25_fu_414_p1));

assign sub_ln21_9_fu_452_p2 = ($signed(sext_ln21_27_fu_434_p1) - $signed(sext_ln21_28_fu_448_p1));

assign sub_ln21_fu_130_p2 = ($signed(sext_ln21_fu_118_p1) - $signed(sext_ln21_1_fu_126_p1));

assign trunc_ln21_10_fu_294_p4 = {{B[47:40]}};

assign trunc_ln21_11_fu_318_p4 = {{A[55:48]}};

assign trunc_ln21_12_fu_332_p4 = {{B[55:48]}};

assign trunc_ln21_13_fu_352_p4 = {{A[63:56]}};

assign trunc_ln21_14_fu_366_p4 = {{B[63:56]}};

assign trunc_ln21_15_fu_390_p4 = {{A[71:64]}};

assign trunc_ln21_16_fu_404_p4 = {{B[71:64]}};

assign trunc_ln21_17_fu_424_p4 = {{A[79:72]}};

assign trunc_ln21_18_fu_438_p4 = {{B[79:72]}};

assign trunc_ln21_19_fu_462_p4 = {{A[87:80]}};

assign trunc_ln21_1_fu_122_p1 = B[7:0];

assign trunc_ln21_20_fu_476_p4 = {{B[87:80]}};

assign trunc_ln21_21_fu_496_p4 = {{A[95:88]}};

assign trunc_ln21_22_fu_510_p4 = {{B[95:88]}};

assign trunc_ln21_23_fu_534_p4 = {{A[103:96]}};

assign trunc_ln21_24_fu_548_p4 = {{B[103:96]}};

assign trunc_ln21_25_fu_568_p4 = {{A[111:104]}};

assign trunc_ln21_26_fu_582_p4 = {{B[111:104]}};

assign trunc_ln21_27_fu_606_p4 = {{A[119:112]}};

assign trunc_ln21_28_fu_620_p4 = {{B[119:112]}};

assign trunc_ln21_29_fu_640_p4 = {{A[127:120]}};

assign trunc_ln21_2_fu_140_p4 = {{A[15:8]}};

assign trunc_ln21_30_fu_654_p4 = {{B[127:120]}};

assign trunc_ln21_3_fu_154_p4 = {{B[15:8]}};

assign trunc_ln21_4_fu_174_p4 = {{A[23:16]}};

assign trunc_ln21_5_fu_188_p4 = {{B[23:16]}};

assign trunc_ln21_6_fu_208_p4 = {{A[31:24]}};

assign trunc_ln21_7_fu_222_p4 = {{B[31:24]}};

assign trunc_ln21_8_fu_246_p4 = {{A[39:32]}};

assign trunc_ln21_9_fu_260_p4 = {{B[39:32]}};

assign trunc_ln21_fu_114_p1 = A[7:0];

assign trunc_ln21_s_fu_280_p4 = {{A[47:40]}};

endmodule //eucHW
